FROM nvidia/opencl:devel-ubuntu16.04

ARG USER_ID
ARG AUTHOR

COPY dist/gocrack/gocrack_server /usr/local/bin/gocrack_server
COPY dist/hashcat/bin/hashcat /usr/local/bin
COPY dist/hashcat/lib/libhashcat.so /usr/local/lib
COPY dist/hashcat/share /usr/local/share
COPY files/server_entrypoint.sh /usr/local/bin/entrypoint.sh

RUN ldconfig

ENTRYPOINT [ "bash", "/usr/local/bin/entrypoint.sh" ]
