FROM nvidia/opencl:devel-ubuntu16.04

COPY dist/gocrack/gocrack_worker /usr/local/bin/gocrack_worker
COPY dist/hashcat/bin/hashcat /usr/local/bin
COPY dist/hashcat/lib/libhashcat.so /usr/local/lib
COPY dist/hashcat/share /usr/local/share
COPY files/worker_entrypoint.sh /usr/local/bin/entrypoint.sh

ENTRYPOINT [ "bash", "/usr/local/bin/entrypoint.sh" ]
